name: workshop
channels:
  - conda-forge
dependencies:
  - jupyterlab
  - jupytext
  - matplotlib
  - napari
  - pip
  - pip:
    - jupyter-book
    - napari-animation
    - "git+https://github.com/kephale/cellpose-napari@cellposev3"

