name: napari-dl-at-mbl-2024
channels:
  - conda-forge
dependencies:
  - "python<3.12"
  - jupyterlab
  - jupytext
  - matplotlib
  - napari
  - pyqt
  - qtpy
  - pip
  - pip:
    - jupyter-book
    - napari-animation
#    - "git+0https://github.com/kephale/cellpose-napari@cellposev3"

